### ISSUE TITLE
Issue in aws vm instantiation

### ISSUE THREAD

**Issue by parulagrawal14** [cloudify-cosmo/cloudify-aws-plugin#193]
Hi,

I am trying to use blueprint for aws. But I am getting below mentioned error.

Little bit about my set up.
My cloudify manager is installed in one of the VM in openstack. I am trying to instantiate VM in aws using cloudify manager of openstack.

Commands used:
cfy blueprints upload -b cassandra-aws-blueprint -p blueprint.yaml ; cfy deployments create -b cassandra-aws-blueprint -d cassandra_aws_dep -i inputs.yaml; cfy executions start -w install -d cassandra_aws_dep

ERROR:
======================================
ec2_region_name: ap-southeast-1
server_image_id: ami-06963965
ssh_username: ubuntu
package_format: rpm
server_instance_type: t2.micro

use_existing_security_group: true
existing_security_group_id: sg-6156111

# The id is required unless you change this to false in which case you must supply the subsequent values.
use_existing_subnet: true
existing_subnet_id: subnet-3ef33050

# The id is required unless you change this to false in which case you must supply the subsequent values.
use_existing_vpc: true
existing_vpc_id: vpc-3e514b5d

======================================

But I am not able to create instance and below error is coming.

2017-02-01T05:57:05 CFY <cassandra_aws_dep> [example_aws_virtual_machine_8fe5c.create] Task failed 'cloudify_aws.ec2.instance.create' -> EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>73c5ea00-1363-4dfa-8777-9931ee32e4dd</RequestID></Response>
2017-02-01T05:57:06 CFY <cassandra_aws_dep> 'install' workflow execution failed: RuntimeError: Workflow failed: Task failed 'cloudify_aws.ec2.instance.create' -> EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>73c5ea00-1363-4dfa-8777-9931ee32e4dd</RequestID></Response>
Execution of workflow install for deployment cassandra_aws_dep failed. [error=Traceback (most recent call last):
  File "/tmp/pip-build-IhIw_h/cloudify-plugins-common/cloudify/dispatch.py", line 472, in _remote_workflow_child_thread
  File "/tmp/pip-build-IhIw_h/cloudify-plugins-common/cloudify/dispatch.py", line 504, in _execute_workflow_function
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/workflows.py", line 27, in install
    node_instances=set(ctx.node_instances))
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 28, in install_node_instances
    processor.install()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 83, in install
    graph_finisher_func=self._finish_install)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 103, in _process_node_instances
    self.graph.execute()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks_graph.py", line 133, in execute
    self._handle_terminated_task(task)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks_graph.py", line 207, in _handle_terminated_task
    raise RuntimeError(message)
RuntimeError: Workflow failed: Task failed 'cloudify_aws.ec2.instance.create' -> EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>73c5ea00-1363-4dfa-8777-9931ee32e4dd</RequestID></Response>
==============================================================

Any idea how can i rectify this issue. Also do i need to install aws plugin locally. What changes I need to make in blueprint for that because by default it will try to install agent which may not be required for local installation of aws blueprint.

I tried with lot of examples ... but none of them worked.

I tried the below github also https://github.com/cloudify-examples/cassandra-blueprint
but same ouput
 Request your guidance.
Any help would be really great.

Thank you.

Thanks and Regards,
Parul

**Comment by ak-ashish14** [comment]
May be it is because the params combination you are passing for the subnet, security group or VPC is not related.
